name: Publication de l'image Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v2

      - name: Installer Buildx
        uses: docker/setup-buildx-action@v1

      - name: Connectez-vous à Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Créer et publier l'image Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bk09/calculatrice:latest
